<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   GET /projects (index - display list of the records)
|   GET /projects/1 (show - display single record)
|   GET /projects/create (create - display the create new record form)
|   GET /projects/1/edit (edit - display the edit record form)
|   POST /projects (store - write in a new record)
|   PATCH /projects/1 (update - update a record)
|   DELETE /projects/1 (destroy - delete a record)
|
*/

Route::get('/', 'PagesController@home');

Route::get('/contact', function () {
    return view('contact');
});
Route::get('/about', function () {
    return view('about');
});

Route::get('/projects', 'ProjectController@index');
Route::get('/projects/create', 'ProjectController@create');
Route::get('/projects/{project}', 'ProjectController@show')->middleware('can:update,project');
Route::get('/projects/{project}/edit', 'ProjectController@edit')->middleware('can:update,project');
Route::post('/projects', 'ProjectController@store')->middleware('can:update,project');
Route::patch('/projects/{project}', 'ProjectController@update')->middleware('can:update,project');
Route::delete('/projects/{project}', 'ProjectController@destroy')->middleware('can:update,project');

Route::post('/projects/{project}/tasks/', 'ProjectTaskController@store')->middleware('can:update,project');
Route::patch('/tasks/{task}', 'ProjectTaskController@update')->middleware('can:update,project');

// Auth related routes generated by Artisan
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
